# Generated by Django 3.2.5 on 2022-06-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_address_1', models.CharField(max_length=10)),
                ('from_address_2', models.CharField(max_length=10)),
                ('from_address_3', models.CharField(max_length=10)),
                ('to_address_1', models.CharField(max_length=10)),
                ('to_address_2', models.CharField(max_length=10)),
                ('to_address_3', models.CharField(max_length=10)),
                ('cost', models.CharField(max_length=200)),
            ],
        ),
    ]
